---
title: "SF3B1 project _coding start"
author: "Shane Warland"
date: "7/14/2020"
output: html_document
---
```{r}
#Access necessary packages
library(data.table)
library(readxl)
library(dplyr)
library(ggplot2)
library(reshape2)
library(ggrepel)
library(tidyverse)
library(gplots)
library(knitr)
library("RColorBrewer")
```



```{r}
#Assigning Number and Denominator Count table

Denoms <- '../output/CountTables/SF3B1MUT_v_Dis.numers.gz'
Numers <- '../output/CountTables/SF3B1MUT_v_Dis.denoms.gz'

#create the count tables
#If .gz add "gunzip -c " to paste0 function
NumeratorCountTable <- fread(paste0(Numers), sep=" ", header=F, data.table=F)
DenominatorCountTable <- fread(paste0(Denoms), sep=" ", header=F, data.table=F)
#head(NumeratorCountTable)
#Create PSI_table and clean up
PSI_Table <- NumeratorCountTable[-1]/DenominatorCountTable[-1]
#head(PSI_Table)
colnames(NumeratorCountTable)[1] <- "chrom"
#gsub(":clu_.+", "", NumeratorCountTable$chrom) %>% head()
row.names(PSI_Table) <- gsub(":clu_.+", "", NumeratorCountTable$chrom)
PSI_Table[is.na(PSI_Table)] <- 0
head(PSI_Table)
PSI_TableNum <- PSI_Table %>% unlist() %>% as.numeric()
#heatmap(PSI_Table)


#Have to add column names for propper sorting later

col_names<-fread(Numers, sep="", quote=F)[1,] %>% colnames()
colnamessplit<- unlist(str_split(col_names," "))

data.table(colnamessplit)
#head(colnamessplit)
colnames(PSI_Table)<-colnamessplit

#Make new variable to see unfiltered
UnfilteredDarman <- PSI_Table
#head(UnfilteredDarman)
#head(PSI_Table)
```
Now lets filter the data based on significant introns identified in Darman et al.
```{r}
#Lets try filtering it by significant introns from Darman
Darman <- read_excel("Darmanhg38.xls", col_names=T)

#used mutate to add 1 to both start and stop columns in Darman in order to clean up mapping 
Darman1 <- Darman %>% mutate(Start=Start+1,End=End+1) 
#Darman1 %>% head()


#combine Darman first 3 columns so it matches
Darman.df <- unite(Darman1, Chrom, c("Chromosome","Start"), sep = ":", remove = TRUE, na.rm = FALSE)
#head(Darman.df)
Darmansorted.df <-  unite(Darman.df, Chrom, c("Chrom","End"), sep = ":", remove = TRUE, na.rm = FALSE)
  #paste(Darman$Chromosome, ":", Darman$Start, ":", Darman$End)
#head(Darmansorted.df)

#Make rowname actual column so I can filter it
PSI_TableRowNamed <- cbind(Chrom = rownames(PSI_Table), PSI_Table)
#PSI_TableRowNamed <- PSI_TableRowNamed[,-1]
#head(PSI_TableRowNamed)
#dat2 <- data_qual[data_qual$ID %in% dat$ID, ]
DarmanFiltered.df <- PSI_TableRowNamed[PSI_TableRowNamed$Chrom %in% Darmansorted.df$Chrom,]

dim(DarmanFiltered.df)
#head(DarmanFiltered.df)

DarmanFinished <- (DarmanFiltered.df %>%data.matrix() %>% as.data.frame() %>% select(-Chrom)%>% as.matrix())
head(DarmanFinished)
```

Run the PCA
```{r}
#Running PC analysis
library(tidyverse)
DarmanFinished = scale(DarmanFinished)
#head(DarmanFinished)
DarmanFinishedUnfil = scale(UnfilteredDarman)
#head(DarmanFinishedUnfil)
# Use "UnfilteredDarman" to see unfiltered result, or "DarmanFinished" to see filtered data
PCResults <- (DarmanFinished) %>%
  #head(100) %>%
  t() %>%
  prcomp(center=T, scale=T)
#head(PCResults)
PCResultsUnfil <- (DarmanFinishedUnfil) %>%
  #head(100) %>%
  t() %>%
  prcomp(center=T, scale=T)
#head(PCResultsUnfil)
#may need to change pc [,1:x] based on how many columns
PCResults.df <- as.data.frame(PCResults$x[,1:7]) %>% rownames_to_column()
PCResultsUnfil.df <- as.data.frame(PCResultsUnfil$x[,1:7]) %>% rownames_to_column()

head(PCResults.df)
head(PCResultsUnfil.df)


```

I have the PCR results but I want to add data from the group file in order to be able to cluster my PC plot by group
This code processes it and adds it
```{r}
#getting rid of ID from group file 
groupfile <- "../data/groupfiles/sf3b1_mut_dis.groups.tsv"
groupfiletable <- read.delim(groupfile, header = F, sep = "\t")
head(groupfiletable)

groupNoID <- data.frame(lapply(groupfiletable, function(x) {gsub("id", "", x)}))

colnames(groupNoID) <- c("rowname", "mutation", "disease")
head(groupNoID,20)


#merging group file
#Using new PCResults
combined.data <- merge(x = PCResults.df, y = groupNoID, by = c("rowname"), all = TRUE)
UnfilCombined <- merge(x = PCResultsUnfil.df, y = groupNoID, by = c("rowname"), all = TRUE)
head(combined.data,20)
```

Now visualize the PCA
```{r}
#PCA graph
PCResultsNoS2.df <- PCResults.df[-c(5,6,11,12),]
ggplot(combined.data) +
  geom_point(aes(x=PC1, y=PC2, color= mutation, shape = disease)) + ggtitle("PCA of Mutants and WTs in different backgrounds")
ggplot(UnfilCombined) +
  geom_point(aes(x=PC1, y=PC2, color= mutation, shape = disease))
```


```{r}
#This was simply used to create bed files to trouble shoot
Darman %>% select("Chromosome","Start","End") %>% 
  write.table("/project2/yangili1/shanewarland/SF3B1_project/DarmanBed.bed",col.names =F, sep = "\t", row.names=F, quote=F)

PSI_Table %>% rownames_to_column() %>% select(rowname) %>% 
  separate(rowname, c("Chromosome","Start","End"), sep=":")%>% write.table("/project2/yangili1/shanewarland/SF3B1_project/PSI_BED.bed",col.names =F, sep = "\t", row.names=F, quote=F)

"chr6:10723241:10724556" %in% PSI_TableRowNamed$Chrom
arrange(Darmansorted.df, `FDR q-value`) %>% head()
```

```{r}
Darman <- read_excel("Darmanhg38.xls", col_names=T)

#used mutate to add 1 to both start and stop columns in Darman in order to clean up mapping 
Darman1 <- Darman %>% mutate(Start=Start+1,End=End+1) 
Darman1 %>% head()
head(PSI_Table)


Heatmap <- PSI_Table %>%
  filter(rownames(.) %in% DifferentialJunctionsList$junc_id) %>%
  dplyr::select(c(Cases, Controls)) %>% as.matrix() %>%
  t() %>% scale(scale=F) %>% t() %>% as.data.frame() %>% drop_na() %>% as.matrix()



```



